version: "3"

services:
  checkers:
    image: checkers_i
    container_name: checkers
    stdin_open: true
    tty: true
    volumes:
      - ${PWD}:/checkers
    working_dir: /checkers
    ports:
      - "1317:1317"
      - "3000:3000"
      - "4500:4500"
      - "5000:5000"
      - "26657:26657"
